#!/usr/bin/env python3
"""Fetch official source references and emit a live drift report."""

from __future__ import annotations

import argparse
import collections
import datetime as dt
import hashlib
import json
import pathlib
import socket
import ssl
import sys
import urllib.error
import urllib.request


REFERENCE_FIELDS = {
    "homepage_url",
    "api_docs_url",
    "key_request_url",
    "notice_url",
    "terms_url",
    "metadata_standard_url",
}

REFERENCE_IMPACT = {
    "homepage_url": ["source_identity"],
    "api_docs_url": ["catalogue", "auth", "runtime"],
    "key_request_url": ["auth"],
    "notice_url": ["notice", "runtime"],
    "terms_url": ["terms"],
    "metadata_standard_url": ["metadata_standard"],
}


def load_json(path: pathlib.Path) -> object:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def as_dict(value: object, path: pathlib.Path) -> dict[str, object]:
    if not isinstance(value, dict):
        raise ValueError(f"{path} must contain a JSON object")
    return value


def utc_now() -> str:
    return dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def drift_status(status: int | None, final_url: str | None, original_url: str) -> str:
    if status is None:
        return "error"
    if status in {404, 410}:
        return "missing"
    if status >= 400:
        return "error"
    if final_url and final_url != original_url:
        return "redirected"
    return "unchanged"


def fetch_reference(url: str, timeout: float) -> dict[str, object]:
    request = urllib.request.Request(
        url,
        headers={
            "User-Agent": "datapan-registry-reference-drift/1.0",
            "Accept": "text/html,application/json,application/xml,text/plain,*/*",
        },
    )
    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            body = response.read()
            status = int(response.status)
            final_url = response.geturl()
            result: dict[str, object] = {
                "last_http_status": status,
                "final_url": final_url,
                "content_hash": hashlib.sha256(body).hexdigest(),
            }
            result["drift_status"] = drift_status(status, final_url, url)
            return result
    except urllib.error.HTTPError as exc:
        body = exc.read() if exc.fp else b""
        result = {
            "last_http_status": int(exc.code),
            "final_url": exc.geturl(),
            "drift_status": drift_status(int(exc.code), exc.geturl(), url),
            "notes": f"http_error: {exc.reason}",
        }
        if body:
            result["content_hash"] = hashlib.sha256(body).hexdigest()
        return result
    except (urllib.error.URLError, TimeoutError, socket.timeout, ssl.SSLError) as exc:
        return {
            "drift_status": "error",
            "notes": f"fetch_error: {exc}",
        }


def profile_references(profile: dict[str, object], profile_path: pathlib.Path) -> list[dict[str, str]]:
    references = as_dict(profile.get("references"), profile_path)
    result: list[dict[str, str]] = []
    for key in sorted(REFERENCE_FIELDS):
        value = references.get(key)
        if isinstance(value, str):
            reviewed_at = references.get("last_reviewed_at")
            if not isinstance(reviewed_at, str):
                raise ValueError(f"{profile_path} references.last_reviewed_at must be a string")
            result.append({"kind": key, "url": value, "reviewed_at": reviewed_at})
    return result


def build_report(profile_paths: list[pathlib.Path], timeout: float) -> tuple[dict[str, object], list[str]]:
    summary: collections.Counter[str] = collections.Counter()
    sources: list[dict[str, object]] = []
    failures: list[str] = []

    for profile_path in profile_paths:
        profile = as_dict(load_json(profile_path), profile_path)
        source_id = profile.get("source_id")
        provider = profile.get("provider")
        if not isinstance(source_id, str) or not isinstance(provider, str):
            raise ValueError(f"{profile_path} must include source_id and provider")

        references = profile_references(profile, profile_path)
        source_entry = {
            "source_id": source_id,
            "provider": provider,
            "source_profile": str(profile_path),
            "last_reviewed_at": references[0]["reviewed_at"] if references else "",
            "references": [],
            "notes": "Live network drift check generated by scripts/check-source-reference-drift.py.",
        }

        for reference in references:
            fetched = fetch_reference(reference["url"], timeout)
            status = fetched.pop("drift_status")
            reference_entry = {
                "kind": reference["kind"],
                "url": reference["url"],
                "reviewed_at": reference["reviewed_at"],
                "check_mode": "network_fetch",
                "drift_status": status,
                "contract_impact": REFERENCE_IMPACT.get(reference["kind"], ["unknown"]),
                **fetched,
            }
            source_entry["references"].append(reference_entry)

            summary["references"] += 1
            summary["network_checked_references"] += 1
            if status in {"changed", "redirected"}:
                summary["changed_references"] += 1
            if status == "missing":
                summary["missing_references"] += 1
            if status in {"changed", "redirected", "missing"}:
                summary["contract_affecting_changes"] += 1
            if status in {"missing", "error"}:
                failures.append(f"{source_id} {reference['kind']} {reference['url']} -> {status}")

        sources.append(source_entry)

    report = {
        "schema_version": "datapan.source-reference-drift.v1",
        "generated_at": utc_now(),
        "summary": {
            "sources": len(sources),
            "references": summary["references"],
            "manual_review_references": 0,
            "network_checked_references": summary["network_checked_references"],
            "changed_references": summary["changed_references"],
            "missing_references": summary["missing_references"],
            "contract_affecting_changes": summary["contract_affecting_changes"],
        },
        "sources": sources,
    }
    return report, failures


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--profiles",
        nargs="*",
        type=pathlib.Path,
        help="source profile files; defaults to sources/*.json",
    )
    parser.add_argument(
        "--output",
        default=".datapan/ci/source-reference-drift-live.json",
        type=pathlib.Path,
        help="path to write the live drift report",
    )
    parser.add_argument(
        "--timeout",
        default=20.0,
        type=float,
        help="per-reference fetch timeout in seconds",
    )
    parser.add_argument(
        "--no-fail",
        action="store_true",
        help="write the report but return success even when references are missing or error",
    )
    args = parser.parse_args()

    profiles = args.profiles or sorted(pathlib.Path("sources").glob("*.json"))
    if not profiles:
        print("no source profiles found", file=sys.stderr)
        return 1

    report, failures = build_report(profiles, args.timeout)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {args.output} (sources={report['summary']['sources']}, references={report['summary']['references']})")

    if failures:
        print("source reference drift failures:", file=sys.stderr)
        for failure in failures:
            print(f"  {failure}", file=sys.stderr)
        return 0 if args.no_fail else 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
