#!/usr/bin/env python3
"""Validate the bounded open-source governance baseline in a source release."""

from __future__ import annotations

import pathlib
import subprocess
import sys


ROOT = pathlib.Path(__file__).resolve().parent.parent
REQUIRED_FILES = (
    "LICENSE",
    "NOTICE",
    "CONTRIBUTING.md",
    "SECURITY.md",
    "TRADEMARKS.md",
    "docs/source-rights.md",
)
REQUIRED_TEXT = {
    "LICENSE": ("Apache License", "Version 2.0, January 2004"),
    "NOTICE": (
        "Datapan-authored",
        "upstream datasets",
        "not a sublicense",
        "docs/source-rights.md",
    ),
    "CONTRIBUTING.md": ("Apache License 2.0", "no separate contributor license agreement"),
    "SECURITY.md": ("No verified private vulnerability-reporting path", "Stop condition:"),
    "TRADEMARKS.md": ("does not grant permission", "does not assert"),
    "docs/source-rights.md": (
        "not an\nupstream-data sublicense",
        "terms_url",
        "prohibited uses",
        "not legal advice",
    ),
    "README.md": (
        "[License](LICENSE)",
        "[Source rights](docs/source-rights.md)",
        "[Contributing](CONTRIBUTING.md)",
        "[Security](SECURITY.md)",
        "[Trademark guidance](TRADEMARKS.md)",
    ),
}


def require(condition: bool, message: str) -> None:
    if not condition:
        raise ValueError(message)


def git_output(*args: str) -> str:
    return subprocess.run(
        ["git", *args], cwd=ROOT, check=True, capture_output=True, text=True
    ).stdout


def validate() -> None:
    for relative in REQUIRED_FILES:
        path = ROOT / relative
        require(path.is_file(), f"required governance file is missing: {relative}")

    for relative, snippets in REQUIRED_TEXT.items():
        text = (ROOT / relative).read_text(encoding="utf-8")
        for snippet in snippets:
            require(snippet in text, f"{relative} is missing required governance text: {snippet!r}")

    # Source releases generated by GitHub include tracked files unless they are
    # marked export-ignore. The data-only release zip intentionally remains
    # manifest-bound and does not become a license carrier for provider data.
    tracked = set(git_output("ls-files", "--", *REQUIRED_FILES).splitlines())
    require(
        tracked == set(REQUIRED_FILES),
        "required governance files must be tracked for source-release inclusion",
    )
    attributes = git_output("check-attr", "export-ignore", "--", *REQUIRED_FILES).splitlines()
    excluded = [line for line in attributes if line.endswith(": set")]
    require(not excluded, f"governance files must not be export-ignored: {', '.join(excluded)}")


def main() -> int:
    try:
        validate()
    except (OSError, subprocess.CalledProcessError, ValueError) as exc:
        print(f"FAIL open-source governance baseline: {exc}", file=sys.stderr)
        return 1
    print("ok open-source governance baseline")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
